server {
    listen 80;
    server_name fededg.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name fededg.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/fededg.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fededg.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://frontend;
    }

    location /api/ {
        proxy_pass http://backend:4000/;
    }
}